name: Release

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
env:
  TZ: Asia/Shanghai

permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        name: Set up JDK 8
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # ref: https://github.com/gradle/gradle-build-action#use-a-specific-gradle-version
          gradle-version: '6.9.4'

      - name: Package with Gradle
        run: gradle clean zip

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: artifact
          path: build/distributions

      - name: metadata
        id: metadata
        run: |
          VERSION=$(gradle -q getVersion)
          REPO=${{ github.repository }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "repo_name=$(echo $REPO | tr '[A-Z]' '[a-z]')"  >> $GITHUB_OUTPUT
      # get isSnapshot from gradle.properties
      - name: isPrerelease
        id: is_prerelease
        run: |
          echo "is_prerelease=$(grep -oP 'isSnapshot=\K.*' gradle.properties)" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v1
        name: Release
        with:
          files: "build/distributions/*.zip"
          body_path: "CHANGELOG.md"
          tag_name: ${{ steps.metadata.outputs.version }}
          prerelease: ${{ steps.is_prerelease.outputs.is_prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Github Container registry
        uses: docker/login-action@v2
        with:
#          Github Container registry: ghcr.io
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.metadata.outputs.repo_name }}:${{ steps.metadata.outputs.version }} , ghcr.io/${{ steps.metadata.outputs.repo_name }}:latest